import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from . import __version__
from .models import AnalysisResult


def file_sha256(path: Optional[Path]) -> Optional[str]:
    if path is None:
        return None
    digest = hashlib.sha256()
    with path.open("rb") as file:
        for chunk in iter(lambda: file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def render_summary_markdown(result: AnalysisResult, generated_at: datetime) -> str:
    stats = result.statistics
    config = result.config
    return "\n".join(
        [
            "# 地面日照分析报告",
            "",
            f"**生成时间**: {generated_at.isoformat()}",
            f"**工具版本**: sunlit {__version__}",
            f"**分析模式**: {result.mode.display_name}",
            "",
            "## 运行参数",
            "",
            f"- 位置: {config.latitude}°, {config.longitude}°",
            f"- 日期: {config.date}",
            f"- 时段: {config.time_start} - {config.time_end}",
            f"- 时间步长: {config.time_step_minutes} 分钟",
            f"- 网格大小: {config.grid_size_meters} m",
            f"- 达标阈值: {config.threshold_hours} 小时",
            "",
            "## 统计结果",
            "",
            f"- 评估点位总数: {stats.total_points}",
            f"- 达标点位: {stats.qualified_points} ({stats.qualified_pct:.2f}%)",
            f"- 达标面积: 约 {stats.qualified_area_sqm:.2f} m²",
            f"- 最大日照时长: {stats.max_hours:.2f} 小时",
            f"- 最小日照时长: {stats.min_hours:.2f} 小时",
            f"- 平均日照时长: {stats.avg_hours:.2f} 小时",
            "",
            "## 工具定位声明",
            "",
            result.disclaimer,
            "",
            f"Generated by sunlit v{__version__}",
            "",
        ]
    )


def render_metadata_yaml(
    result: AnalysisResult,
    generated_at: datetime,
    scheme_path: Optional[Path],
    context_path: Optional[Path],
    boundary_path: Path,
    timezone_name: str,
) -> str:
    lines = [
        f"version: {__version__}",
        f"generated_at: {generated_at.isoformat()}",
        f"mode: {result.mode.display_name}",
        f"timezone: {timezone_name}",
        "inputs:",
        f"  scheme: {str(scheme_path) if scheme_path else ''}",
        f"  scheme_sha256: {file_sha256(scheme_path) or ''}",
        f"  context: {str(context_path) if context_path else ''}",
        f"  context_sha256: {file_sha256(context_path) or ''}",
        f"  boundary: {boundary_path}",
        f"  boundary_sha256: {file_sha256(boundary_path) or ''}",
        "config:",
        f"  latitude: {result.config.latitude}",
        f"  longitude: {result.config.longitude}",
        f"  date: {result.config.date}",
        f"  time_start: {result.config.time_start}",
        f"  time_end: {result.config.time_end}",
        f"  time_step_minutes: {result.config.time_step_minutes}",
        f"  grid_size_meters: {result.config.grid_size_meters}",
        f"  threshold_hours: {result.config.threshold_hours}",
        "outputs:",
        "  analysis: analysis.json",
        "  heatmap: heatmap.png",
        "  summary: summary.md",
    ]
    return "\n".join(lines) + "\n"


def write_report_files(
    result: AnalysisResult,
    output_dir: Path,
    scheme_path: Optional[Path],
    context_path: Optional[Path],
    boundary_path: Path,
    timezone_name: str,
) -> tuple[Path, Path]:
    generated_at = datetime.now(timezone.utc)
    summary_path = output_dir / "summary.md"
    metadata_path = output_dir / "metadata.yaml"
    summary_path.write_text(render_summary_markdown(result, generated_at), encoding="utf-8")
    metadata_path.write_text(
        render_metadata_yaml(
            result=result,
            generated_at=generated_at,
            scheme_path=scheme_path,
            context_path=context_path,
            boundary_path=boundary_path,
            timezone_name=timezone_name,
        ),
        encoding="utf-8",
    )
    return summary_path, metadata_path

